---
title: Парсер, скраппер, краулер и запоминание других стрёмных слов
output: html_document
---



Идеология курса 
===================

Нашёл на этой страничке ошибку? Нашёл какой-то ультраполезный ресурс? Придумал какое-то интересное задание для семинара? Есть конструктивная критика? Не молчи, напиши мне об этом на почту filfonul@gmail.com, в Telegram (@Ppilif) или  [Вконтакте](https://vk.com/ppilif).

-------------------------------------------------

Agenda
------------------
1. Обо всём и ни о чём!  Введение в LaTeX.  Мотивация изучать LaTeX. Немного о разных движках (PdfTex, XeTeX и т.д.). Математика в LaTeX.
2. XeTeX. Немного подробнее о шрифтах. Что такое юникод? Рисунки и таблицы в LaTeX. Booktabs.
3. Графика (Tikz). Великая и могучая Geogebra. Собственные команды и макросы.
4. Оформление документа в целом. Некоторые странные пакеты. Minted.
5. Список литературы, bibtex. Преамбула для души и преамбула по ГОСТ. Пакет biblatex-gost.
6. Сбор одного файла из нескольких разных. R + LaTeX — самая мощная связка в мире! Красивая эконометрика. Пара слов о "Make-файлах" в R.  Markdown.  Несколько слов об Atom. 
7. R + LaTeX — продолжаем разговор! Автоматизация создания документов. Как создать 100 красивых анкет для игры в киллера в один клик?
8. Презентации в LaTeX — большая боль или чувство стиля? Ультрановомодный Atom. Из Wolfram да прямо в LaTeX.


Лицензия
----------
Созданные для данного курса материалы распространяются по лицензии [Do What The Fuck You Want To Public License (WTFPL)](http://www.wtfpl.net/)




